name: SSH Deploy to Docker

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "production"
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        env:
          SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: SHA
          script: |
            echo ${{ secrets.DOCKER_TOKEN }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
            DOCKER_IMAGE_TAG=${SHA:0:7}
            docker pull siavashoutadi/backstage-demo:$DOCKER_IMAGE_TAG
            docker stop backstage-demo || true
            docker rm backstage-demo || true
            docker run -d --name backstage-demo -p 9000:8080 siavashoutadi/backstage-demo:$DOCKER_IMAGE_TAG
